steps:
# Auth is handled by gcloud so we don't need to do anything
- name: gcr.io/cloud-builders/gcloud
  args:
  - 'artifacts'
  - 'go'
  - 'upload'
  - '--project=hanzhenyi3'
  - '--location=europe-west1'
  - '--repository=go-repo'
  - '--module-path=github.com/yihanzhen/gcb-go-push'
  # Set version to tag name because it is a convention for Go to use git tags
  # as version numbers.
  # The $TAG is a feature of GCB to substitute the playholder to the actual tag name
  # if the build script is set to trigger on push to a tag.
  - '--version=$TAG_NAME'